[config]
version-name = "debug"
based-on = "lernstick-mini.toml"

[lb-config]
chroot-squashfs-compression-level = 1

[excludes]
# Exclude most packages that are not needed to check if live build works correctly
package-lists = [
    "debian_contrib-default.list.chroot",
    "debian_main-standard.list.chroot",
    "lernstick-standard.list.chroot",
    "libreoffice-core.list.chroot",
    "itch.list.chroot",
    "signal.list.chroot",
    "lernstick-games.list.chroot",
    "printing.list.chroot",
    "education.list.chroot",
    "games.list.chroot",
    "lernstick-education.list.chroot",
    "lernstick-enlightenment.list.chroot",
    "enlightenment.list.chroot",
    "lernstick-xfce.list.chroot",
    "xfce.list.chroot",
    "lernstick-mate.list.chroot",
    "mate.list.chroot",
    "lxde.list.chroot",
    "lernstick-lxde.list.chroot",
    "debian_non-free.list.chroot",
    "lernstick-cinnamon.list.chroot",
    "cinnamon.list.chroot"
    ]
hooks = []
